import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  CheckCircle2,
  Clipboard,
  Clock,
  Cloud,
  Cpu,
  Database,
  Eye,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  Globe,
  Heart,
  Home,
  Info,
  Layers,
  LayoutDashboard,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Network,
  Package,
  PieChart,
  Plug,
  Puzzle,
  Rocket,
  Rss,
  Search,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Target,
  Terminal,
  TrendingUp,
  Upload,
  User,
  Users,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icon whitelist for plugins.
 *
 * Plugins reference icons by name (manifest/contribution data crosses a
 * serialization boundary, so they cannot pass component references). The
 * host resolves names from this fixed list; unknown names fall back to the
 * puzzle piece.
 */

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  archive: Archive,
  'bar-chart': BarChart3,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  check: CheckCircle2,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  file: FileText,
  flag: Flag,
  gauge: Gauge,
  'git-branch': GitBranch,
  globe: Globe,
  heart: Heart,
  home: Home,
  info: Info,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  link: Link,
  list: List,
  lock: Lock,
  mail: Mail,
  map: Map,
  'message-square': MessageSquare,
  network: Network,
  package: Package,
  'pie-chart': PieChart,
  plug: Plug,
  puzzle: Puzzle,
  rocket: Rocket,
  rss: Rss,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  terminal: Terminal,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

export function resolvePluginIcon(name: string | undefined): LucideIcon {
  if (!name) return Puzzle;
  return ICONS[name.toLowerCase()] ?? Puzzle;
}

export const PLUGIN_ICON_NAMES = Object.keys(ICONS);
